module.exports = {
  title: 'Styleguide',

  // theme folder
  themeFolder: '../app/design/frontend/Mygento/nespresso',

  // a url path to the static files generated by Magento
  staticUrl: 'static/version1547030519/frontend/Mygento/nespresso/ru_RU',

  // a relative path to where files with kss markdown are to be found
  source: ['../app/design/frontend/Mygento/nespresso/web/scss/', './src/app/docs'],

  // relative path to the project's pub folder
  destination: '../../nespresso-workplace/application/pub/styleguide/',

  // path to company logo relative to theme images folder
  placeholder: 'nespresso-white.svg',

  // leave as is unless you need to modify the app
  builder: 'src/app/',
  css: [
    'kss-assets/css/styleguide.css'
  ],
  js: [
    'kss-assets/js/kss.js'
  ],
};
